// This file is generated by scripts/build-minim-icons.mjs.
// Edit the source SVG files or generator, then run npm run icons:build.

import * as React from "react"

export interface CatalogIconProps
  extends Omit<React.ComponentPropsWithoutRef<"svg">, "children"> {
  variant?: "default" | "selected"
  title?: string
}

export const CatalogIcon = React.forwardRef<SVGSVGElement, CatalogIconProps>(
  function CatalogIcon(
    { variant = "default", title, width = "1em", height = "1em", ...props },
    ref
  ) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width={width}
        height={height}
        fill="currentColor"
        role={title ? "img" : undefined}
        aria-hidden={title ? undefined : true}
        focusable="false"
        {...props}
      >
        {title ? <title>{title}</title> : null}
        {variant === "selected" ? (
          <>
            <rect x="0" width="24" height="24" rx="6" ry="6"/>
              <g>
                <path fill="#fff" d="M16.17,8.82c-.75,0-1.48.14-2.18.39V3.95H4.07s-1.84,0-1.84,0v11.76l5.83,5.84h1.83v-4.61c.73,2.79,3.26,4.85,6.27,4.85,3.57,0,6.48-2.91,6.48-6.49s-2.91-6.49-6.48-6.49ZM11.99,5.95v4.4s-.03.03-.04.04c-.23.2-.44.4-.64.63-.04.04-.08.09-.11.14-.17.2-.32.41-.46.63-.03.04-.06.08-.09.13-.16.26-.31.53-.43.82-.01.03-.02.05-.03.08-.11.27-.21.54-.28.83,0,.01,0,.03-.01.04v-3.44l-3.97-4.28h6.06ZM4.24,7.07l3.66,3.95v2.68h-3.66v-6.63ZM5.05,15.7h2.85v2.86l-2.85-2.86ZM16.17,19.8c-2.48,0-4.49-2.01-4.49-4.49,0-.16,0-.31.03-.5.13-1.26.81-2.41,1.85-3.15.77-.55,1.67-.83,2.6-.83,2.47,0,4.48,2.01,4.48,4.49s-2.01,4.49-4.48,4.49Z"/>
                <path fill="#fff" d="M16.16,14.03c-.71,0-1.29.57-1.29,1.28s.58,1.29,1.29,1.29,1.28-.58,1.28-1.29-.57-1.28-1.28-1.28Z"/>
              </g>
          </>
        ) : (
          <>
            <path d="M16.17,8.82c-.75,0-1.48.14-2.18.39V3.95H4.07s-1.84,0-1.84,0v11.76l5.83,5.84h1.83v-4.61c.73,2.79,3.26,4.85,6.27,4.85,3.57,0,6.48-2.91,6.48-6.49s-2.91-6.49-6.48-6.49ZM11.99,5.95v4.4s-.03.03-.04.04c-.23.2-.44.4-.64.63-.04.04-.08.09-.11.14-.17.2-.32.41-.46.63-.03.04-.06.08-.09.13-.16.26-.31.53-.43.82-.01.03-.02.05-.03.08-.11.27-.21.54-.28.83,0,.01,0,.03-.01.04v-3.44l-3.97-4.28h6.06ZM4.24,7.07l3.66,3.95v2.68h-3.66v-6.63ZM5.05,15.7h2.85v2.86l-2.85-2.86ZM16.17,19.8c-2.48,0-4.49-2.01-4.49-4.49,0-.16,0-.31.03-.5.13-1.26.81-2.41,1.85-3.15.77-.55,1.67-.83,2.6-.83,2.47,0,4.48,2.01,4.48,4.49s-2.01,4.49-4.48,4.49Z"/>
              <path d="M16.16,14.03c-.71,0-1.29.57-1.29,1.28s.58,1.29,1.29,1.29,1.28-.58,1.28-1.29-.57-1.28-1.28-1.28Z"/>
          </>
        )}
      </svg>
    )
  }
)
