// This file is generated by scripts/build-minim-icons.mjs.
// Edit the source SVG files or generator, then run npm run icons:build.

import * as React from "react"

export interface Explore2IconProps
  extends Omit<React.ComponentPropsWithoutRef<"svg">, "children"> {
  variant?: "default" | "selected"
  title?: string
}

export const Explore2Icon = React.forwardRef<SVGSVGElement, Explore2IconProps>(
  function Explore2Icon(
    { variant = "default", title, width = "1em", height = "1em", ...props },
    ref
  ) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width={width}
        height={height}
        fill="currentColor"
        role={title ? "img" : undefined}
        aria-hidden={title ? undefined : true}
        focusable="false"
        {...props}
      >
        {title ? <title>{title}</title> : null}
        {variant === "selected" ? (
          <>
            <rect x="0" width="24" height="24" rx="6" ry="6"/>
              <g>
                <path fill="#fff" d="M12,17.87c-5.35,0-9.53-5.03-9.71-5.24l-.52-.63.52-.63c.17-.21,4.36-5.24,9.71-5.24s9.53,5.03,9.71,5.24l.52.63-.52.63c-.18.21-4.36,5.24-9.71,5.24ZM4.42,12c1.22,1.24,4.21,3.88,7.58,3.88s6.36-2.63,7.58-3.88c-1.22-1.24-4.21-3.87-7.58-3.87s-6.36,2.63-7.58,3.87Z"/>
                <path fill="#fff" d="M12,15.07c-1.69,0-3.07-1.38-3.07-3.07s1.38-3.07,3.07-3.07,3.07,1.38,3.07,3.07-1.38,3.07-3.07,3.07ZM12,10.93c-.59,0-1.07.48-1.07,1.07s.48,1.07,1.07,1.07,1.07-.48,1.07-1.07-.48-1.07-1.07-1.07Z"/>
              </g>
          </>
        ) : (
          <>
            <path d="M12,17.87c-5.35,0-9.53-5.03-9.71-5.24l-.52-.63.52-.63c.17-.21,4.36-5.24,9.71-5.24s9.53,5.03,9.71,5.24l.52.63-.52.63c-.18.21-4.36,5.24-9.71,5.24ZM4.42,12c1.22,1.24,4.21,3.88,7.58,3.88s6.36-2.63,7.58-3.88c-1.22-1.24-4.21-3.87-7.58-3.87s-6.36,2.63-7.58,3.87Z"/>
              <path d="M12,15.07c-1.69,0-3.07-1.38-3.07-3.07s1.38-3.07,3.07-3.07,3.07,1.38,3.07,3.07-1.38,3.07-3.07,3.07ZM12,10.93c-.59,0-1.07.48-1.07,1.07s.48,1.07,1.07,1.07,1.07-.48,1.07-1.07-.48-1.07-1.07-1.07Z"/>
          </>
        )}
      </svg>
    )
  }
)
