// This file is generated by scripts/build-minim-icons.mjs.
// Edit the source SVG files or generator, then run npm run icons:build.

import * as React from "react"

export interface Minim4IconProps
  extends Omit<React.ComponentPropsWithoutRef<"svg">, "children"> {
  variant?: "default" | "selected"
  title?: string
}

export const Minim4Icon = React.forwardRef<SVGSVGElement, Minim4IconProps>(
  function Minim4Icon(
    { variant = "default", title, width = "1em", height = "1em", ...props },
    ref
  ) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width={width}
        height={height}
        fill="currentColor"
        role={title ? "img" : undefined}
        aria-hidden={title ? undefined : true}
        focusable="false"
        {...props}
      >
        {title ? <title>{title}</title> : null}
        {variant === "selected" ? (
          <>
            <rect width="24" height="24" rx="6" ry="6"/>
              <g>
                <rect fill="#fff" x="4.1" y="4.86" width="15.8" height="2"/>
                <rect fill="#fff" x="4.1" y="7.93" width="15.8" height="2"/>
                <rect fill="#fff" x="4.1" y="11" width="15.8" height="2"/>
                <rect fill="#fff" x="4.1" y="14.07" width="15.8" height="2"/>
                <rect fill="#fff" x="4.1" y="17.14" width="15.8" height="2"/>
              </g>
          </>
        ) : (
          <>
            <rect x="4.1" y="4.86" width="15.8" height="2"/>
              <rect x="4.1" y="7.93" width="15.8" height="2"/>
              <rect x="4.1" y="11" width="15.8" height="2"/>
              <rect x="4.1" y="14.07" width="15.8" height="2"/>
              <rect x="4.1" y="17.14" width="15.8" height="2"/>
          </>
        )}
      </svg>
    )
  }
)
