// This file is generated by scripts/build-minim-icons.mjs.
// Edit the source SVG files or generator, then run npm run icons:build.

import * as React from "react"

export interface Minim6IconProps
  extends Omit<React.ComponentPropsWithoutRef<"svg">, "children"> {
  variant?: "default" | "selected"
  title?: string
}

export const Minim6Icon = React.forwardRef<SVGSVGElement, Minim6IconProps>(
  function Minim6Icon(
    { variant = "default", title, width = "1em", height = "1em", ...props },
    ref
  ) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width={width}
        height={height}
        fill="currentColor"
        role={title ? "img" : undefined}
        aria-hidden={title ? undefined : true}
        focusable="false"
        {...props}
      >
        {title ? <title>{title}</title> : null}
        {variant === "selected" ? (
          <>
            <rect x="0" width="24" height="24" rx="6" ry="6"/>
              <g>
                <polygon fill="#fff" points="19.9 6.86 19.9 6.86 4.1 4.86 19.9 4.86 19.9 6.86"/>
                <polygon fill="#fff" points="19.9 9.93 19.9 9.93 4.1 7.93 19.9 7.93 19.9 9.93"/>
                <polygon fill="#fff" points="19.9 13 19.9 13 4.1 11 19.9 11 19.9 13"/>
                <polygon fill="#fff" points="19.9 16.07 19.9 16.07 4.1 14.07 19.9 14.07 19.9 16.07"/>
                <polygon fill="#fff" points="19.9 19.14 19.9 19.14 4.1 17.14 19.9 17.14 19.9 19.14"/>
              </g>
          </>
        ) : (
          <>
            <polygon points="19.9 6.86 19.9 6.86 4.1 4.86 19.9 4.86 19.9 6.86"/>
              <polygon points="19.9 9.93 19.9 9.93 4.1 7.93 19.9 7.93 19.9 9.93"/>
              <polygon points="19.9 13 19.9 13 4.1 11 19.9 11 19.9 13"/>
              <polygon points="19.9 16.07 19.9 16.07 4.1 14.07 19.9 14.07 19.9 16.07"/>
              <polygon points="19.9 19.14 19.9 19.14 4.1 17.14 19.9 17.14 19.9 19.14"/>
          </>
        )}
      </svg>
    )
  }
)
