// This file is generated by scripts/build-minim-icons.mjs.
// Edit the source SVG files or generator, then run npm run icons:build.

import * as React from "react"

import { Minim1Icon } from "@/registry/default/minim-icons/minim-1-icon"
import { Minim2Icon } from "@/registry/default/minim-icons/minim-2-icon"
import { Minim3Icon } from "@/registry/default/minim-icons/minim-3-icon"
import { Minim4Icon } from "@/registry/default/minim-icons/minim-4-icon"
import { Minim5Icon } from "@/registry/default/minim-icons/minim-5-icon"
import { Minim6Icon } from "@/registry/default/minim-icons/minim-6-icon"
import { LibraryIcon } from "@/registry/default/minim-icons/library-icon"
import { CatalogIcon } from "@/registry/default/minim-icons/catalog-icon"
import { SearchIcon } from "@/registry/default/minim-icons/search-icon"
import { ExploreIcon } from "@/registry/default/minim-icons/explore-icon"
import { Explore2Icon } from "@/registry/default/minim-icons/explore-2-icon"
import { NotificationIcon } from "@/registry/default/minim-icons/notification-icon"
import { ProfileIcon } from "@/registry/default/minim-icons/profile-icon"
import { Profile2Icon } from "@/registry/default/minim-icons/profile-2-icon"
import { SettingsIcon } from "@/registry/default/minim-icons/settings-icon"
import { Settings2Icon } from "@/registry/default/minim-icons/settings-2-icon"
import { LeftIcon } from "@/registry/default/minim-icons/left-icon"
import { RightIcon } from "@/registry/default/minim-icons/right-icon"
import { UpIcon } from "@/registry/default/minim-icons/up-icon"
import { DownIcon } from "@/registry/default/minim-icons/down-icon"

export {
  Minim1Icon,
  Minim2Icon,
  Minim3Icon,
  Minim4Icon,
  Minim5Icon,
  Minim6Icon,
  LibraryIcon,
  CatalogIcon,
  SearchIcon,
  ExploreIcon,
  Explore2Icon,
  NotificationIcon,
  ProfileIcon,
  Profile2Icon,
  SettingsIcon,
  Settings2Icon,
  LeftIcon,
  RightIcon,
  UpIcon,
  DownIcon,
}

export const iconNames = [
  "minim-1",
  "minim-2",
  "minim-3",
  "minim-4",
  "minim-5",
  "minim-6",
  "library",
  "catalog",
  "search",
  "explore",
  "explore-2",
  "notification",
  "profile",
  "profile-2",
  "settings",
  "settings-2",
  "left",
  "right",
  "up",
  "down",
] as const

export type IconName = (typeof iconNames)[number]
export type IconVariant = "default" | "selected"

const iconComponents = {
  "minim-1": Minim1Icon,
  "minim-2": Minim2Icon,
  "minim-3": Minim3Icon,
  "minim-4": Minim4Icon,
  "minim-5": Minim5Icon,
  "minim-6": Minim6Icon,
  "library": LibraryIcon,
  "catalog": CatalogIcon,
  "search": SearchIcon,
  "explore": ExploreIcon,
  "explore-2": Explore2Icon,
  "notification": NotificationIcon,
  "profile": ProfileIcon,
  "profile-2": Profile2Icon,
  "settings": SettingsIcon,
  "settings-2": Settings2Icon,
  "left": LeftIcon,
  "right": RightIcon,
  "up": UpIcon,
  "down": DownIcon,
} as const

export interface MinimIconProps
  extends Omit<React.ComponentPropsWithoutRef<"svg">, "children"> {
  name: IconName
  variant?: IconVariant
  title?: string
}

export const MinimIcon = React.forwardRef<SVGSVGElement, MinimIconProps>(
  function MinimIcon({ name, variant = "default", ...props }, ref) {
    const Icon = iconComponents[name]

    return <Icon ref={ref} variant={variant} {...props} />
  }
)
