// This file is generated by scripts/build-minim-icons.mjs.
// Edit the source SVG files or generator, then run npm run icons:build.

import * as React from "react"

export interface Profile2IconProps
  extends Omit<React.ComponentPropsWithoutRef<"svg">, "children"> {
  variant?: "default" | "selected"
  title?: string
}

export const Profile2Icon = React.forwardRef<SVGSVGElement, Profile2IconProps>(
  function Profile2Icon(
    { variant = "default", title, width = "1em", height = "1em", ...props },
    ref
  ) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width={width}
        height={height}
        fill="currentColor"
        role={title ? "img" : undefined}
        aria-hidden={title ? undefined : true}
        focusable="false"
        {...props}
      >
        {title ? <title>{title}</title> : null}
        {variant === "selected" ? (
          <>
            <rect x="0" width="24" height="24" rx="6" ry="6"/>
              <g>
                <path fill="#fff" d="M19,20h-2v-9c0-2.76-2.24-5-5-5s-5,2.24-5,5v9h-2v-9c0-3.86,3.14-7,7-7s7,3.14,7,7v9Z"/>
                <path fill="#fff" d="M16,20h-2v-9c0-1.1-.9-2-2-2s-2,.9-2,2v9h-2v-9c0-2.21,1.79-4,4-4s4,1.79,4,4v9Z"/>
                <path fill="#fff" d="M13,20h-2v-9c0-.55.45-1,1-1h0c.55,0,1,.45,1,1v9Z"/>
              </g>
          </>
        ) : (
          <>
            <path d="M19,22h-2v-11c0-2.76-2.24-5-5-5s-5,2.24-5,5v11h-2v-11c0-3.86,3.14-7,7-7s7,3.14,7,7v11Z"/>
              <path fill="#fff" stroke="currentColor" strokeMiterlimit="10" strokeWidth="2px" d="M6,22v-11c0-3.31,2.69-6,6-6s6,2.69,6,6v11"/>
              <path d="M16,22h-2v-11c0-1.1-.9-2-2-2s-2,.9-2,2v11h-2v-11c0-2.21,1.79-4,4-4s4,1.79,4,4v11Z"/>
              <path d="M13,22h-2v-11c0-.55.45-1,1-1h0c.55,0,1,.45,1,1v11Z"/>
          </>
        )}
      </svg>
    )
  }
)
