// This file is generated by scripts/build-minim-icons.mjs.
// Edit the source SVG files or generator, then run npm run icons:build.

import * as React from "react"

export interface ProfileIconProps
  extends Omit<React.ComponentPropsWithoutRef<"svg">, "children"> {
  variant?: "default" | "selected"
  title?: string
}

export const ProfileIcon = React.forwardRef<SVGSVGElement, ProfileIconProps>(
  function ProfileIcon(
    { variant = "default", title, width = "1em", height = "1em", ...props },
    ref
  ) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width={width}
        height={height}
        fill="currentColor"
        role={title ? "img" : undefined}
        aria-hidden={title ? undefined : true}
        focusable="false"
        {...props}
      >
        {title ? <title>{title}</title> : null}
        {variant === "selected" ? (
          <>
            <rect width="24" height="24" rx="6" ry="6"/>
              <g>
                <path fill="#fff" d="M18.94,19.65c-1.85-1.85-4.32-2.88-6.94-2.88s-5.09,1.02-6.94,2.88l-1.41-1.41c4.61-4.61,12.11-4.61,16.72,0l-1.41,1.41Z"/>
                <path fill="#fff" d="M16.79,13.63H7.21V4.06h9.57v9.57ZM9.21,11.63h5.57v-5.57h-5.57v5.57Z"/>
              </g>
          </>
        ) : (
          <>
            <path d="M18.94,20.19c-3.83-3.83-10.06-3.83-13.89,0l-1.41-1.41c4.61-4.61,12.11-4.61,16.72,0l-1.41,1.41Z"/>
              <path d="M16.79,14.16H7.21V4.59h9.57v9.57ZM9.21,12.16h5.57v-5.57h-5.57v5.57Z"/>
          </>
        )}
      </svg>
    )
  }
)
