// This file is generated by scripts/build-minim-icons.mjs.
// Edit the source SVG files or generator, then run npm run icons:build.

import * as React from "react"

export interface RightIconProps
  extends Omit<React.ComponentPropsWithoutRef<"svg">, "children"> {
  variant?: "default" | "selected"
  title?: string
}

export const RightIcon = React.forwardRef<SVGSVGElement, RightIconProps>(
  function RightIcon(
    { variant = "default", title, width = "1em", height = "1em", ...props },
    ref
  ) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width={width}
        height={height}
        fill="currentColor"
        role={title ? "img" : undefined}
        aria-hidden={title ? undefined : true}
        focusable="false"
        {...props}
      >
        {title ? <title>{title}</title> : null}
        {variant === "selected" ? (
          <>
            <rect x="0" width="24" height="24" rx="6" ry="6"/>
              <g>
                <path fill="#fff" d="M18.36,12c-3.49,0-6.32-2.84-6.32-6.32h2c0,2.38,1.94,4.32,4.32,4.32v2Z"/>
                <path fill="#fff" d="M14.04,18.33h-2c0-3.49,2.84-6.32,6.32-6.32v2c-2.38,0-4.32,1.94-4.32,4.32Z"/>
                <rect fill="#fff" x="5.64" y="11" width="12.39" height="2"/>
              </g>
          </>
        ) : (
          <>
            <path d="M18.36,12c-3.49,0-6.32-2.84-6.32-6.32h2c0,2.38,1.94,4.32,4.32,4.32v2Z"/>
              <path d="M14.04,18.33h-2c0-3.49,2.84-6.32,6.32-6.32v2c-2.38,0-4.32,1.94-4.32,4.32Z"/>
              <rect x="5.64" y="11" width="12.39" height="2"/>
          </>
        )}
      </svg>
    )
  }
)
