// This file is generated by scripts/build-minim-icons.mjs.
// Edit the source SVG files or generator, then run npm run icons:build.

import * as React from "react"

export interface SearchIconProps
  extends Omit<React.ComponentPropsWithoutRef<"svg">, "children"> {
  variant?: "default" | "selected"
  title?: string
}

export const SearchIcon = React.forwardRef<SVGSVGElement, SearchIconProps>(
  function SearchIcon(
    { variant = "default", title, width = "1em", height = "1em", ...props },
    ref
  ) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width={width}
        height={height}
        fill="currentColor"
        role={title ? "img" : undefined}
        aria-hidden={title ? undefined : true}
        focusable="false"
        {...props}
      >
        {title ? <title>{title}</title> : null}
        {variant === "selected" ? (
          <>
            <rect y="-.06" width="24" height="24" rx="6" ry="6"/>
              <rect width="24" height="24" rx="6" ry="6"/>
              <g>
                <path fill="#fff" d="M11.68,19.4c-1.99,0-3.87-.78-5.28-2.19-2.91-2.91-2.91-7.65,0-10.56,1.41-1.41,3.28-2.19,5.28-2.19s3.87.78,5.28,2.19c2.91,2.91,2.91,7.65,0,10.56-1.41,1.41-3.28,2.19-5.28,2.19ZM11.68,6.48c-1.46,0-2.83.57-3.86,1.6-1.03,1.03-1.6,2.4-1.6,3.86s.57,2.83,1.6,3.86c1.03,1.03,2.4,1.6,3.86,1.6s2.83-.57,3.86-1.6c2.13-2.13,2.13-5.6,0-7.73-1.03-1.03-2.4-1.6-3.86-1.6Z"/>
                <rect fill="#fff" x="16.52" y="15.98" width="2" height="3.59" transform="translate(-7.44 17.6) rotate(-45.01)"/>
              </g>
          </>
        ) : (
          <>
            <path d="M11.94,19.4c-1.99,0-3.87-.78-5.28-2.19-2.91-2.91-2.91-7.65,0-10.56,1.41-1.41,3.28-2.19,5.28-2.19s3.87.78,5.28,2.19c2.91,2.91,2.91,7.65,0,10.56-1.41,1.41-3.28,2.19-5.28,2.19ZM11.94,6.48c-1.46,0-2.83.57-3.86,1.6-2.13,2.13-2.13,5.6,0,7.73,1.03,1.03,2.4,1.6,3.86,1.6s2.83-.57,3.86-1.6c1.03-1.03,1.6-2.4,1.6-3.86s-.57-2.83-1.6-3.86c-1.03-1.03-2.4-1.6-3.86-1.6Z"/>
              <rect x="16.78" y="15.98" width="2" height="3.59" transform="translate(-7.36 17.78) rotate(-45.01)"/>
          </>
        )}
      </svg>
    )
  }
)
